name: scRNA-benchmark
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - numpy>=1.24
  - pandas>=2.0
  - matplotlib>=3.8
  - seaborn>=0.13
  - scikit-learn>=1.3
  - tqdm>=4.65
  - scanpy>=1.10
  - anndata>=0.10
  - umap-learn>=0.5.5
  - pymde>=0.1.15


